//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MassiveEmailSender.Language {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ru_RU {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ru_RU() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MassiveEmailSender.Language.ru-RU", typeof(ru_RU).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на  Открыто!.
        /// </summary>
        internal static string _____4Open_ {
            get {
                return ResourceManager.GetString("\\\\\\\\\\4Open!", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Желаете сбросить настройки? [Да/Нет] .
        /// </summary>
        internal static string Are_you_want_reset_setting___Yes_No______4 {
            get {
                return ResourceManager.GetString("Are you want reset setting? [Yes/No]\\\\\\\\\\4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Проверте настройки перед запуском программы .
        /// </summary>
        internal static string Check_setting_before_program_start_____4 {
            get {
                return ResourceManager.GetString("Check setting before program start\\\\\\\\\\4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Конфигурация завершена!.
        /// </summary>
        internal static string Configuration_complite_ {
            get {
                return ResourceManager.GetString("Configuration complite!", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Создание клиента ... .
        /// </summary>
        internal static string Creating_client_________4 {
            get {
                return ResourceManager.GetString("Creating client ...\\\\\\\\\\4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Введите адресс smtp сервера вашего email.
        /// </summary>
        internal static string Enter_email_smtp_server_address {
            get {
                return ResourceManager.GetString("Enter email smtp server address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Введите пароль от email.
        /// </summary>
        internal static string Enter_password_from_email {
            get {
                return ResourceManager.GetString("Enter password from email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Введите ваш email адресс.
        /// </summary>
        internal static string Enter_your_email_address {
            get {
                return ResourceManager.GetString("Enter your email address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Утилита Massive Email Sender.
        /// </summary>
        internal static string Massive_Email_Sender_Utility {
            get {
                return ResourceManager.GetString("Massive Email Sender Utility", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Успешно!.
        /// </summary>
        internal static string OK_ {
            get {
                return ResourceManager.GetString("OK!", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Открытие файла .
        /// </summary>
        internal static string Opening_____4 {
            get {
                return ResourceManager.GetString("Opening\\\\\\\\\\4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Нажмите любую клавишу для продолжения.
        /// </summary>
        internal static string Press_any_key_to_continue {
            get {
                return ResourceManager.GetString("Press any key to continue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Нажмите любую клавишу для запуска утилиты.
        /// </summary>
        internal static string Press_any_key_to_start_utility {
            get {
                return ResourceManager.GetString("Press any key to start utility", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Работа программы завершена. Нажните любую клавишу что-бы закрыть окно.
        /// </summary>
        internal static string Program_work_endded__Press_any_key_to_close {
            get {
                return ResourceManager.GetString("Program work endded. Press any key to close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Чтение конфигурации ... .
        /// </summary>
        internal static string Reading_config_________4 {
            get {
                return ResourceManager.GetString("Reading config ...\\\\\\\\\\4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Чтение сообщения ... .
        /// </summary>
        internal static string Reading_message_________4 {
            get {
                return ResourceManager.GetString("Reading message ...\\\\\\\\\\4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Сброс настроек ... .
        /// </summary>
        internal static string Reseting_settings_________4 {
            get {
                return ResourceManager.GetString("Reseting settings ...\\\\\\\\\\4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Отправка соосбщений .
        /// </summary>
        internal static string Sending_emails_____4 {
            get {
                return ResourceManager.GetString("Sending emails\\\\\\\\\\4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Напишите все целевые email адресса в файл через перенос строк.
        /// </summary>
        internal static string Write_all_target_emails_to_file_throught_line_break {
            get {
                return ResourceManager.GetString("Write all target emails to file throught line break", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Напишите сообщение в html файл.
        /// </summary>
        internal static string Write_message_to_html_file {
            get {
                return ResourceManager.GetString("Write message to html file", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Запись в файл ... .
        /// </summary>
        internal static string Writting_to_file_________4 {
            get {
                return ResourceManager.GetString("Writting to file ...\\\\\\\\\\4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Да.
        /// </summary>
        internal static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
    }
}
